// Code generated by go generate; DO NOT EDIT.

package random

import "fmt"
import "strconv"

type ContinuousDistribution struct {
	Doc     string
	Sampler func(*Random, []string) (func() float64, error)
}

type DiscreteDistribution struct {
	Doc     string
	Sampler func(*Random, []string) (func() int64, error)
}

var ContinuousRegistry = map[string]ContinuousDistribution{
	"BETA": {
		Doc: "Distribution: Beta\n\nParameters:\n- nu: shape parameter (>0)\n- omega: shape parameter (>0)\n\nThe probability density function is\n\nf(x) = x^(nu-1) * (1-x)^(omega-1) / B(nu, omega),  for 0 ≤ x ≤ 1\n= 0,                                          otherwise\n\nwhere B(nu, omega) = Gamma(nu) * Gamma(omega) / Gamma(nu + omega) is\nthe Beta function, and Gamma() is the Gamma function.\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			nu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable nu=" + spar[0])
			}
			omega, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable omega=" + spar[1])
			}
			return rng.GetBetaSampler(nu, omega)
		},
	},
	"CAUCHY": {
		Doc: "Distribution: Cauchy\n\nParameters:\n- a: location parameter (the median)\n- b: scale parameter (> 0).\n\nThe probability density function is:\n\nf(x) = 1 / (pi * b) / (1 + ((x - a)/b)^2),  for -∞ < x < ∞\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			return rng.GetCauchySampler(a, b)
		},
	},
	"CHISQ": {
		Doc: "Distribution: Chi squared\n\nParameters:\n- nu: shape parameter (degrees of freedom, nu > 0).\n\nThe probability density function is:\n\nf(x) = 2^(-nu/2) / Gamma(nu/2) * x^(nu/2 - 1) * e^(-x/2),  for 0 ≤ x < ∞\n= 0,                                               otherwise\n\nwhere Gamma() is the Gamma function.\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			nu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable nu=" + spar[0])
			}
			return rng.GetChiSqSampler(nu)
		},
	},
	"ERLANG": {
		Doc: "Distribution: Erlang\n\nParameters:\n- lambda: rate parameter (> 0)\n- k: number of stages k (> 0, integer).\n\nThe probability density function is:\n\nf(x) = lambda^k / (k-1)! * x^(k-1) * exp(-lambda * x),  for x ≥ 0\n= 0,                                               otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			lambda, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable lambda=" + spar[0])
			}
			k, err1 := strconv.ParseInt(spar[1], 10, 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable k=" + spar[1])
			}
			return rng.GetErlangSampler(lambda, k)
		},
	},
	"EXPONENTIAL": {
		Doc: "Distribution: Exponential\n\nParameters:\n- lambda: rate parameter (> 0)\n\nThe probability density function is:\n\nf(x) = lambda * exp(-lambda * x),  for x ≥ 0\n= 0,                          otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			lambda, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable lambda=" + spar[0])
			}
			return rng.GetExponentialSampler(lambda)
		},
	},
	"F": {
		Doc: "Distribution: F\n\nParameters:\n- d1: degree of freedom (>0)\n- d2: degree of freedom d2 (> 0)\n\nThe probability density function is:\n\nf(x) = (d1/d2)^(d1/2) * x^(d1/2 - 1) / B(d1/2, d2/2) *\n(1 + d1*x/d2)^(-(d1+d2)/2),  for x ≥ 0\n= 0,                           otherwise\n\nwhere B(y, z) = Gamma(y) * Gamma(z) / Gamma(y + z) is\nthe Beta function, and Gamma() is the Gamma function.\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			d1, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable d1=" + spar[0])
			}
			d2, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable d2=" + spar[1])
			}
			return rng.GetFSampler(d1, d2)
		},
	},
	"GAMMA": {
		Doc: "Distribution: Gamma\n\nParameters:\n- alpha: shape parameter (>0)\n- theta: scale parameter (>0)\n\nThe probability density function is:\n\nf(x) = x^(alpha-1) * exp(-x/theta) / (Gamma(alpha) * theta^alpha),  for x ≥ 0\n= 0,                                                          otherwise\n\nwhere Gamma() is the Gamma function.\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			alpha, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable alpha=" + spar[0])
			}
			theta, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable theta=" + spar[1])
			}
			return rng.GetGammaSampler(alpha, theta)
		},
	},
	"GUMBEL": {
		Doc: "Distribution: Gumbel (Extreme value distribution)\n\nParameters:\n- a: location parameter\n- b: scale parameter (>0)\n\nThe probability density function is:\n\nf(x) = exp(-z - exp(-(x-a)/b)) / b,  for -∞ < x < ∞\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			return rng.GetGumbelSampler(a, b)
		},
	},
	"INVERSEGAUSSIAN": {
		Doc: "Distribution: Inverse Gaussian\n\nParameters:\n- mu: mean (>0)\n- lambda: shape parameter (>0)\n\nThe probability density function is:\n\nf(x) = sqrt(lambda / (2*pi*x^3)) * exp(-lambda*(x-mu)^2 / (2*mu^2*x)),  for x > 0\n= 0,                                                               otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			mu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable mu=" + spar[0])
			}
			lambda, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable lambda=" + spar[1])
			}
			return rng.GetInverseGaussianSampler(mu, lambda)
		},
	},
	"LAPLACE": {
		Doc: "Distribution: Laplace(a,b) (double exponential)\n\nParameters:\n- a: location parameter\n- b: scale parameter (> 0)\n\nPDF:\n\nf(x) = (1 / (2 b)) exp(-|x − a| / b),  for −∞ < x < ∞\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			return rng.GetLaplaceSampler(a, b)
		},
	},
	"LOGISTIC": {
		Doc: "Distribution: Logistic\n\nParameters:\n- a : location parameter\n- b : scale parameter  (>0)\n\nThe probability density function is:\n\nf(x) = exp(-(x-a)/b) / (b * (1 + exp(-(x-a)/b))^2),  for -∞ < x < ∞\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			return rng.GetLogisticSampler(a, b)
		},
	},
	"LOGNORMAL": {
		Doc: "Distribution: Lognormal\n\nParameters:\n- mu: mean of the logarithm of the random variable\n- sigmaL: standard deviation of the logarithm of the random variable (>0)\n\nThe probability density function is:\n\nf(x) = 1 / (sigma x sqrt(2*pi)) *\nexp(-(ln(x)-mu)^2 / (2*sigma^2)),  for x > 0\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			mu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable mu=" + spar[0])
			}
			sigma, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable sigma=" + spar[1])
			}
			return rng.GetLognormalSampler(mu, sigma)
		},
	},
	"NORMAL": {
		Doc: "Distribution: Normal (Gaussian)\n\nParameters:\n- mu: mean\n- sigma:standard deviation (> 0)\n\nThe probability density function is:\n\nf(x) = 1 / sqrt(2 * pi * sigma^2) *\nexp(-(x - mu)^2 / (2 * sigma^2)),  for -∞ < x < ∞\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			mu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable mu=" + spar[0])
			}
			sigma, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable sigma=" + spar[1])
			}
			return rng.GetNormalSampler(mu, sigma)
		},
	},
	"PARETO": {
		Doc: "Distribution: Pareto\n\nParameters:\n- a: scale parameter a (>0)\n- c: shape parameter c (> 0).\n\nThe probability density function is:\n\nf(x) = c * a^c / x^(c + 1),  for x >= a\n= 0,                     otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			c, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable c=" + spar[1])
			}
			return rng.GetParetoSampler(a, c)
		},
	},
	"POWER": {
		Doc: "Distribution: Power\n\nParameters:\n- b: scale parameter b (>0)\n- c: shape parameter c (>0)\n\nThe probability density function is:\n\nf(x) = c * x^(c-1)/b^c,  for 0 <= x <= b\n= 0,                otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			b, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[0])
			}
			c, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable c=" + spar[1])
			}
			return rng.GetPowerSampler(b, c)
		},
	},
	"RAYLEIGH": {
		Doc: "Distribution: Rayleigh\n\nParameters:\n- b: scale parameter (>0)\n\nThe probability density function is:\n\nf(x) = x / b^2 * exp(-x^2 / (2 * b^2)),  for 0 <= x < ∞\n= 0,                                otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			b, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[0])
			}
			return rng.GetRayleighSampler(b)
		},
	},
	"T": {
		Doc: "Distribution: T\n\nParameters:\n- nu: degrees of freedom (>0)\n\nThe probability density function is:\n\nf(x) = Γ((nu+1)/2) / (Γ(nu/2) * sqrt(pi * nu)) *\n(1 + x^2/nu)^(-(nu+1)/2),  for -∞ < x < ∞\n\nExample usage:\n\nsampler, _ := r.GetTSampler(2.0)\nx := sampler()\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			nu, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable nu=" + spar[0])
			}
			return rng.GetTSampler(nu)
		},
	},
	"TRIANGULAR": {
		Doc: "Distribution: Triangular\n\nParameters:\n- a: minimum\n- b: maximum ( b > a)\n- c: mode (a ≤ c ≤ b)\n\nThe density function is\n\nf(x) = 2 (x - a) / ((b - a)(c - a)),   for a ≤ x ≤ c\n= 2 (b - x) / ((b - a)(b - c)),   for c < x ≤ b\n= 0,                              otherwise\n\nExample usage:\n\nsampler, _ := r.GetTriangularSampler(1.0, 3.0, 2.0)\nx := sampler()\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			c, err2 := strconv.ParseFloat(spar[2], 64)
			if err2 != nil {
				return nil, fmt.Errorf("Unable to parse variable c=" + spar[2])
			}
			return rng.GetTriangularSampler(a, b, c)
		},
	},
	"UNIFORM": {
		Doc: "Distribution: Uniform (Rectangular)\n\nParameters:\n- a: minimum\n- b: maximum (b>a)\n\nThe density function is:\n\nf(x) = 1/(b-a),   for a <= x <= b\n= 0,         otherwise\n\nExample usage:\n\nsampler,_ := r.GetUniformSampler(1.0, 2.0)\nx := sampler()\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			a, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable a=" + spar[0])
			}
			b, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable b=" + spar[1])
			}
			return rng.GetUniformSampler(a, b)
		},
	},
	"WEIBULL": {
		Doc: "Distribution: Weibull\n\nParameters:\n- lambda: scale (>0)\n- k: shape (>0)\n\nThe density function is\n\nf(x) = (k/lambda) (x/lambda)^(k-1) exp(-(x/lambda)^k),   for x ≥ 0\n= 0,                                 otherwise\n\nExample usage:\n\nsampler, _ := r.GetWeibullSampler(1.0, 2.0)\nx := sampler()\n",
		Sampler: func(rng *Random, spar []string) (func() float64, error) {
			lambda, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable lambda=" + spar[0])
			}
			k, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable k=" + spar[1])
			}
			return rng.GetWeibullSampler(lambda, k)
		},
	},
}

var DiscreteRegistry = map[string]DiscreteDistribution{
	"BERNOULLI": {
		Doc: "Distribution: Bernoulli\n\nParameters:\n- p: success probability (0 ≤ p ≤ 1).\n\nThe probability mass function is\n\nf(x) = 1 - p,  for x = 0\n= p,      for x = 1\n= 0,      otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			p, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable p=" + spar[0])
			}
			return rng.GetBernoulliSampler(p)
		},
	},
	"BINOMIAL": {
		Doc: "Distribution: Binomial\n\nParameters:\n- n: number of trials (>0, integer)\n- p: success probability (0 < p < 1).\n\nThe probability mass function is\n\nf(x) = C(n, x) * p^x * (1-p)^(n-x),  for x = 0, ..., n\n= 0,                        otherwise\n\nwhere C(n, x) = n! / (x! (n-x)!) is the binomial coefficient.\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			n, err0 := strconv.ParseInt(spar[0], 10, 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable n=" + spar[0])
			}
			p, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable p=" + spar[1])
			}
			return rng.GetBinomialSampler(n, p)
		},
	},
	"GEOMETRIC": {
		Doc: "Distribution: Geometric\n\nParameters:\n- p: success probability (0 < p ≤ 1).\n\nThe probability mass function is:\n\np(x) = p * (1-p)^(x-1),  for x = 1, 2, 3, ...\n= 0,                  otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			p, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable p=" + spar[0])
			}
			return rng.GetGeometricSampler(p)
		},
	},
	"LOGARITHMIC": {
		Doc: "Distribution: Logarithmic series distribution\n\nParameters:\n- c: shape parameter (0<c<1)\n\nThe probability mass function is:\n\nf(x) = c^x / (x * log(1/(1-c))),  for x = 1, 2, 3, ...\n= 0,                         otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			c, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable c=" + spar[0])
			}
			return rng.GetLogarithmicSampler(c)
		},
	},
	"NEGATIVEBINOMIAL": {
		Doc: "Distribution: Negative Binomial\n\nParameters:\n- r: number of successes r (>0, can be real)\n- p: success probability (0 < p ≤ 1)\n\nThe probability mass function is:\n\nf(x) = Gamma(r + x) / (Gamma(r) * x!) * p^r * (1-p)^x,  for x = 0, 1, 2, ...\n= 0,                                                otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			r, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable r=" + spar[0])
			}
			p, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable p=" + spar[1])
			}
			return rng.GetNegativeBinomialSampler(r, p)
		},
	},
	"PASCAL": {
		Doc: "Distribution: Pascal\n\nParameters:\n- r: number of successes r (>0, integer)\n- p: success probability (0 < p ≤ 1)\n\nThe probability mass function is:\n\nf(x) = Gamma(r + x) / (Gamma(r) * Gamma(x + 1)) *\np^r * (1 - p)^x,  for x = 0, 1, 2, ...\n= 0,                 otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			r, err0 := strconv.ParseInt(spar[0], 10, 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable r=" + spar[0])
			}
			p, err1 := strconv.ParseFloat(spar[1], 64)
			if err1 != nil {
				return nil, fmt.Errorf("Unable to parse variable p=" + spar[1])
			}
			return rng.GetPascalSampler(r, p)
		},
	},
	"POISSON": {
		Doc: "Distribution: Poisson\n\nParameters:\n- lambda: mean (≥0)\n\nThe probability mass function is:\n\nf(x) = λ^x * exp(-λ) / x!,  for x = 0, 1, 2, ...\n= 0,                   otherwise\n",
		Sampler: func(rng *Random, spar []string) (func() int64, error) {
			lambda, err0 := strconv.ParseFloat(spar[0], 64)
			if err0 != nil {
				return nil, fmt.Errorf("Unable to parse variable lambda=" + spar[0])
			}
			return rng.GetPoissonSampler(lambda)
		},
	},
}
