package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type DistInfo struct {
	Name       string
	Doc        string
	Sampler    string
	ReturnType string
}

func main() {
	pkgDir := "." // root random package
	fset := token.NewFileSet()

	var dists []DistInfo

	err := filepath.Walk(pkgDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, "_gen.go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || !strings.HasPrefix(fn.Name.Name, "Get") || !strings.HasSuffix(fn.Name.Name, "Sampler") {
				continue
			}
			dists = append(dists, DistInfo{
				Name:       strings.ToUpper(strings.TrimSuffix(strings.TrimPrefix(fn.Name.Name, "Get"), "Sampler")),
				Doc:        extractDoc(fn.Doc),
				Sampler:    getSamplerCode(fn),
				ReturnType: getReturnType(fn),
			})
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

	var buf bytes.Buffer
	if err := registryTemplate.Execute(&buf, dists); err != nil {
		panic(err)
	}

	out := filepath.Join(pkgDir, "registry_gen.go")
	if err := os.WriteFile(out, buf.Bytes(), 0644); err != nil {
		panic(err)
	}

	fmt.Println("Generated", out)
}

func getSamplerCode(fn *ast.FuncDecl) string {
	var params []struct{ Name, Type string }
	for _, f := range fn.Type.Params.List {
		typ := f.Type.(*ast.Ident).Name // YOU control this, so safe
		for _, name := range f.Names {
			params = append(params, struct{ Name, Type string }{
				Name: name.Name,
				Type: typ,
			})
		}
	}
	returnType := getReturnType(fn)

	var out []string
	out = append(out, fmt.Sprintf("func(rng *Random, spar []string) (func() %s, error){", returnType))
	for i, v := range params {
		switch v.Type {
		case "int64":
			out = append(out, fmt.Sprintf("\t\t\t%s, err%d := strconv.ParseInt(spar[%d], 10, 64)", v.Name, i, i))
			out = append(out, fmt.Sprintf("\t\t\tif err%d!=nil {\n\t\t\t  return nil, fmt.Errorf(\"Unable to parse variable %s=\"+spar[%d])\n\t\t\t}", i, v.Name, i))
		case "float64":
			out = append(out, fmt.Sprintf("\t\t\t %s, err%d := strconv.ParseFloat(spar[%d], 64)", v.Name, i, i))
			out = append(out, fmt.Sprintf("\t\t\t if err%d!=nil {\n\t\t\t   return nil, fmt.Errorf(\"Unable to parse variable %s=\"+spar[%d])\n\t\t\t}", i, v.Name, i))
		}
	}
	names := make([]string, len(params))
	for i, p := range params {
		names[i] = p.Name
	}
	out = append(out, "\t\t\treturn rng."+fn.Name.Name+"("+strings.Join(names, ", ")+")")
	return strings.Join(out, "\n")
}

// getReturnType returns the return type of a function fn
func getReturnType(fn *ast.FuncDecl) string {
	ft := fn.Type.Results.List[0].Type.(*ast.FuncType)
	ret := ft.Results.List[0].Type.(*ast.Ident).Name
	return ret // "float64" or "int64"
}

// extractDoc returns the Doc string of the function starting at the first line
// that starts with "Distribution" and excluding all lines from the line that
// starts with "Example" onwards.
func extractDoc(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}
	lines := strings.Split(doc.Text(), "\n")
	var out []string
	start := false
	for _, l := range lines {
		l = strings.TrimSpace(l)
		if strings.HasPrefix(l, "Distribution:") {
			start = true
		}
		if strings.HasPrefix(l, "Example:") {
			break
		}
		if start {
			out = append(out, l)
		}
	}
	return strings.Join(out, "\n")
}

var registryTemplate = template.Must(template.New("registry").Parse(`
// Code generated by go generate; DO NOT EDIT.

package random

import "fmt"
import "strconv"


type ContinuousDistribution struct {
	Doc  string
	Sampler func(*Random, []string) (func() float64, error)
}

type DiscreteDistribution struct {
	Doc  string
	Sampler func(*Random,[]string) (func() int64, error)
}

var ContinuousRegistry = map[string]ContinuousDistribution{
{{- range . }}
{{- if eq .ReturnType "float64" }}
	"{{ .Name }}": {
		Doc: {{ printf "%q" .Doc }},
		Sampler: {{ printf "%s" .Sampler}}
		},
	},
{{- end }}
{{- end }}
}

var DiscreteRegistry = map[string]DiscreteDistribution{
{{- range . }}
{{- if eq .ReturnType "int64" }}
	"{{ .Name }}": {
		Doc: {{ printf "%q" .Doc }},
		Sampler: {{ printf "%s" .Sampler}}
		},
	},
{{- end }}
{{- end }}
}
`))
